---
version: 0.2
phases:
  pre_build:
    commands:
      - sudo rm -rf ~/Library/Caches/com.docker.docker ~/Library/Cookies/com.docker.docker.binarycookies ~/Library/Group\ Containers/group.com.docker ~/Library/Logs/Docker\ Desktop ~/Library/Preferences/com.docker.docker.plist ~/Library/Preferences/com.electron.docker-frontend.plist ~/Library/Saved\ Application\ State/com.electron.docker-frontend.savedState ~/.docker /Library/LaunchDaemons/com.docker.vmnetd.plist /Library/PrivilegedHelperTools/com.docker.vmnetd /usr/local/lib/docker
      - echo loggin in to amazon ECR
      - docker login https://hub.docker.com -u mulki12 -p 12Februari@ 
  build:
    commands:
      - echo Build started on date
      - echo Building the Docker image...          
      - docker build . -t anjasmara-service-users-v1
      - docker images
      - docker tag anjasmara-service-users-v1 $AWS_ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/anjasmara-service-users-v1:latest
  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/anjasmara-service-users-v1
      - printf '[{"name":"(task_definition)","imageUri":"%s"}]' ($AWS_ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json

    
