---
version: 0.2
phases:
  install:
    commands:
      - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64.tar.gz -O - | tar xz && mv yq_linux_amd64 /usr/bin/yq;
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install --update
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY
      - aws configure set aws_secret_access_key $AWS_SECRET_KEY
      - "aws eks update-kubeconfig --region ap-southeast-1 --name $EKS_CLUSTER_NAME" 
      - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.26.12/2024-01-04/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
      - echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 679381888694.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on date
      - echo Building the Docker image...  
      - COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -b -8)     
      - docker build -t test-laravel:latest .
      - docker tag test-laravel:latest 679381888694.dkr.ecr.ap-southeast-1.amazonaws.com/test-laravel:$COMMIT_ID
  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing the Docker image...
      - docker push 679381888694.dkr.ecr.ap-southeast-1.amazonaws.com/test-laravel:$COMMIT_ID
      - yq e -i '.spec.template.spec.containers[].image = "679381888694.dkr.ecr.ap-southeast-1.amazonaws.com/test-laravel:'"$COMMIT_ID"'"' deployment/deployment.yml
      - kubectl apply -f deployment/
artifacts:
    files: 
      - imagedefinitions.json
      - build.json
      - deployment/*
