---
version: 0.2
phases:
  pre_build:
    commands:
      - sudo rm -rf ~/Library/Caches/com.docker.docker ~/Library/Cookies/com.docker.docker.binarycookies ~/Library/Group\ Containers/group.com.docker ~/Library/Logs/Docker\ Desktop ~/Library/Preferences/com.docker.docker.plist ~/Library/Preferences/com.electron.docker-frontend.plist ~/Library/Saved\ Application\ State/com.electron.docker-frontend.savedState ~/.docker /Library/LaunchDaemons/com.docker.vmnetd.plist /Library/PrivilegedHelperTools/com.docker.vmnetd /usr/local/lib/docker
      - echo login in to amazon ECR
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 221047265242.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on date
      - echo Building the Docker image...          
      - docker build . -t test-laravel
      - docker image 
      - COMMIT_HASH=$(git rev-parse --short HEAD)
      - IMAGE_TAG=:${COMMIT_HASH}
     - docker tag test-laravel 221047265242.dkr.ecr.ap-southeast-1.amazonaws.com/test-laravel:latest $IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing the Docker image...
      - docker push $IMAGE_TAG
##      - printf '[{"name":"(task_definition)","imageUri":"%s"}]' ($AWS_ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json

    
