apiVersion: v1
kind: Namespace
metadata:
  name: dev
spec:
  template:
    spec:
      containers:
        - image: 679381888694.dkr.ecr.ap-southeast-1.amazonaws.com/test-laravel:v2
        - image: 679381888694.dkr.ecr.ap-southeast-1.amazonaws.com/test-laravel:v2
        - image: 679381888694.dkr.ecr.ap-southeast-1.amazonaws.com/test-laravel:v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-laravel
  namespace: dev
  labels:
    app: test-laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-laravel
  template:
    metadata:
      labels:
        app: test-laravel
    spec:
      containers:
        - name: test-laravel
          image: 679381888694.dkr.ecr.ap-southeast-1.amazonaws.com/test-laravel:v2
          ports:
            - containerPort: 3001
        - image: 679381888694.dkr.ecr.ap-southeast-1.amazonaws.com/test-laravel:v2
        - image: 679381888694.dkr.ecr.ap-southeast-1.amazonaws.com/test-laravel:v2
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: test-laravel
  namespace: dev
spec:
  selector:
    app: test-laravel
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 32303
  template:
    spec:
      containers:
        - image: 679381888694.dkr.ecr.ap-southeast-1.amazonaws.com/test-laravel:v2
        - image: 679381888694.dkr.ecr.ap-southeast-1.amazonaws.com/test-laravel:v2
        - image: 679381888694.dkr.ecr.ap-southeast-1.amazonaws.com/test-laravel:v2
