
   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anjasmara-service-general-deployment
  namespace: health-check
  labels:
    app: anjasmara-service-general
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anjasmara-service-general
  template:
    metadata:
      labels:
        app: anjasmara-service-general 
    spec:
      containers:
      - name: anjasmara-service-general
        image: 221047265242.dkr.ecr.ap-southeast-1.amazonaws.com/test-laravel:**BUILD_ID**
        ports:
        - containerPort: 3001
      imagePullSecrets:
          - name: regcred       
---

apiVersion: v1
kind: Service
metadata:
  name: anjasmara-service-general
  namespace: health-check
spec:
  selector:
    app: anjasmara-service-general 
  type: NodePort
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 32303
