

apiVersion: v1
kind: Namespace
metadata:
  name: dev

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-laravel
  namespace: dev
  labels:
    app: test-laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-laravel
  template:
    metadata:
      labels:
        app: test-laravel 
    spec:
      containers:
      - name: test-laravel
        image: 221047265242.dkr.ecr.ap-southeast-1.amazonaws.com/test-laravel:$COMMIT_ID
        ports:
        - containerPort: 3001
      imagePullSecrets:
          - name: regcred       
---

apiVersion: v1
kind: Service
metadata:
  name: test-laravel
  namespace: health-check
spec:
  selector:
    app: test-laravel 
  type: NodePort
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 32303
