apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-laravel
  namespace: dev
  labels:
    app: test-laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-laravel
  template:
    metadata:
      labels:
        app: test-laravel 
    spec:
      containers:
      - name: test-laravel
        image: 679381888694.dkr.ecr.ap-southeast-1.amazonaws.com/test-laravel:$COMMIT_ID
        ports:
        - containerPort: 3001
      imagePullSecrets:
          - name: regcred