apiVersion: v1
kind: Service
metadata:
  name: test-laravel
  namespace: dev
spec:
  selector:
    app: test-laravel 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 32303